### ISSUE TITLE
Unit Testing from the DTK

### ISSUE THREAD

**Issue by bussyjd** [Stacktical/stacktical-dsla-developer-toolkit#38]
## IMPROVEMENT
The DTK should run the Units tests covering the Critical features towards 100% coverage.

#### EXPECTED BEHAVIOR
Running `hh test` would run all the units tests.

#### CURRENT BEHAVIOR
No tests are implemented.

Rationale:
- All in one place to run the tests against different networks
- Control over the different moving parts of the protocol

**Comment by lucarlig** [comment]
won't do, we have unit tests directly in the contracts repository
